"""add text column to generations table

Revision ID: 0d842a727b12
Revises: 5e904d89fea0
Create Date: 2025-09-15 05:55:11.615452

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0d842a727b12"
down_revision: Union[str, Sequence[str], None] = "5e904d89fea0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generations",
        sa.Column(
            "text",
            sa.String(),
            server_default=sa.text("'Generation error'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generations", "text")
    # ### end Alembic commands ###
