"""make text column nullable in generations

Revision ID: 1921fa9fb20e
Revises: d81074bf4707
Create Date: 2025-09-19 16:11:47.745354

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1921fa9fb20e"
down_revision: Union[str, Sequence[str], None] = "d81074bf4707"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "generations",
        "text",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_server_default=sa.text("'Generation error'::character varying"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "generations",
        "text",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_server_default=sa.text("'Generation error'::character varying"),
    )
    # ### end Alembic commands ###
