"""add message column to generations table

Revision ID: 19669a280d3f
Revises: 0d842a727b12
Create Date: 2025-09-19 15:18:40.123424

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "19669a280d3f"
down_revision: Union[str, Sequence[str], None] = "0d842a727b12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("generations", sa.Column("message", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generations", "message")
    # ### end Alembic commands ###
