"""add generation params and rename text column

Revision ID: 4334015aa100
Revises: 1921fa9fb20e
Create Date: 2025-09-26 06:35:22.271476

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4334015aa100"
down_revision: Union[str, Sequence[str], None] = "1921fa9fb20e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generations", sa.Column("generated_text", sa.String(), nullable=True)
    )
    op.add_column(
        "generations",
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_generations_params_gin",
        "generations",
        [sa.literal_column("params")],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_column("generations", "text")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generations",
        sa.Column(
            "text",
            sa.VARCHAR(),
            server_default=sa.text("'Generation error'::character varying"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(
        "ix_generations_params_gin", table_name="generations", postgresql_using="gin"
    )
    op.drop_column("generations", "params")
    op.drop_column("generations", "generated_text")
    # ### end Alembic commands ###
