"""add prompt and model_name columns to generations table

Revision ID: d81074bf4707
Revises: 19669a280d3f
Create Date: 2025-09-19 15:35:44.770384

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d81074bf4707"
down_revision: Union[str, Sequence[str], None] = "19669a280d3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("generations", sa.Column("prompt", sa.String(), nullable=False))
    op.add_column("generations", sa.Column("model_name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generations", "model_name")
    op.drop_column("generations", "prompt")
    # ### end Alembic commands ###
